spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        #native:
         # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/tempy79/microservices.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071


